/*
 * generated by Xtext
 */
package org.xtext.example.compoNantes;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.example.compoNantes.ui.internal.MyDslActivator.getInstance().getInjector("org.xtext.example.compoNantes.MyDsl");
	}
	
}
