/*
 * generated by Xtext
 */
package org.xtext.example.compoNantes.ui.contentassist

import org.xtext.example.compoNantes.ui.contentassist.AbstractCompoNantesProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CompoNantesProposalProvider extends AbstractCompoNantesProposalProvider {
}
