/*
 * generated by Xtext
 */
package org.xtext.example.compoNantes.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CompoNantesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/example/compoNantes/parser/antlr/internal/InternalCompoNantes.tokens");
	}
}
