/*
 * generated by Xtext
 */
package org.xtext.example.compoNantes.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.compoNantes.ui.internal.CompoNantesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CompoNantesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CompoNantesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CompoNantesActivator.getInstance().getInjector(CompoNantesActivator.ORG_XTEXT_EXAMPLE_COMPONANTES_COMPONANTES);
	}
	
}
