/**
 * generated by Xtext
 */
package org.xtext.example.compoNantes.validation;

import org.xtext.example.compoNantes.validation.AbstractMyDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyDslValidator extends AbstractMyDslValidator {
}
