/*
 * generated by Xtext
 */
package org.xtext.example.compoNantes;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CompoNantesStandaloneSetup extends CompoNantesStandaloneSetupGenerated{

	public static void doSetup() {
		new CompoNantesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

