/*
 * generated by Xtext
 */
package org.xtext.example.compoNantes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CompoNantesUiModule extends org.xtext.example.compoNantes.ui.AbstractCompoNantesUiModule {
	public CompoNantesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
